# HumanEval Benchmark Configuration - Fancy

OpenAIHandler:
  cost_limit: 200.0

Agent:
  fsm: simple
  action_select_strat: smart
  patience: 5
  agent_api: false

Logger:
  include_caller_info: rome

MultiAgent:
  agent_role_json: role_config/minimal_roles.json
