# HumanEval Benchmark Configuration - Fancy

OpenAIHandler:
  cost_limit: 200.0

Agent:
  agent_api: false

  action_select_strat: original
  fsm_type: knowledge_base
  patience: 4

  use_ground_truth: True
  save_insights: True
  query_insights: True

Logger:
  include_caller_info: rome

MultiAgent:
  agent_role_json: role_config/minimal_roles2.json
