# HumanEval Benchmark Configuration - Fancy

OpenAIHandler:
  cost_limit: 200.0

Agent:
  agent_api: false

  action_select_strat: original
  fsm_type: knowledge_base
  patience: 4

  use_ground_truth: False
  save_insights: False
  query_insights: True

ChromaClientManager:
  # collection_name: 9_19_knowledge_base_single
  collection_name: 9_18_knowledge_base_multi

Logger:
  include_caller_info: rome

MultiAgent:
  agent_role_json: role_config/minimal_roles.json
