# HumanEval Benchmark Configuration - Basic

OpenAIHandler:
  cost_limit: 500.0

Agent:
  name: "PythonCodeExpert"
  role: "You are an expert Python developer tasked with implementing functions to pass all given test cases. Focus on writing clean, efficient, and well-tested code that handles edge cases properly."
  agent_api: false

  action_select_strat: original
  fsm_type: knowledge_base
  patience: 5

  use_ground_truth: True
  save_insights: True
  query_insights: False

Logger:
  include_caller_info: "rome"
